server:
  servlet:
     context-path: /spring-data
  port: 9000
  
spring:
  application:
    name: spring-data
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties.hibernate.dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    properties.hibernate.enable_lazy_load_no_trans: true
  datasource:
    platform: mysql
    url: jdbc:mysql://localhost:3306/spring_data_example
    username: root
    password: ${SQL_PASSWORD}
    driverClassName: com.mysql.cj.jdbc.Driver
    
springdoc:
  swagger-ui:
    path: /swagger-ui
    