server:
  servlet:
     context-path: /spring-data
  port: 9000
  
spring:
  application:
    name: spring-data
  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties.hibernate.dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    properties.hibernate.enable_lazy_load_no_trans: true
  datasource:
    platform: mysql
    url: ${SQL_PASSWORD}
    username: root
    password: Srduicukzh1
    driverClassName: com.mysql.cj.jdbc.Driver
    
springdoc:
  swagger-ui:
    path: /swagger-ui
    
    

connection-request-timeout: 5000
read-timeout: 5000